language: rust
rust:
  - stable
os: linux
# add nodejs for ganche-cli
node_js: "12.12.0"
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
env:
  global:
    - CARGO_MAKE_RUN_CHECK_FORMAT="true"
    - CARGO_MAKE_RUN_CLIPPY="true"
services:
  - redis

stages:
  - test
  - deploy

jobs:
  fast_finish: true
  include:
    - stage: test
      script:
        - which cargo-make || cargo install cargo-make
        - cargo make ci-flow
      # But don't cache the cargo registry
      before_cache:
        - rm -rf /home/travis/.cargo/registry
    - stage: deploy
      if: tag IS present
      before_deploy:
        - cargo build -p validator_worker --release --all-features --target x86_64-unknown-linux-gnu
        - cp target/x86_64-unknown-linux-gnu/release/validator_worker validator_worker-v$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_API_TOKEN
        file: $TRAVIS_BUILD_DIR/validator_worker-v$TRAVIS_TAG
        skip_cleanup: true
        draft: true
        on:
          tags: true
          all_branches: true