[package]
name = "sentry"
version = "0.1.0"
authors = ["Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[dependencies]
# Futures
futures = "0.3.1"
async-std = "1.4.0"
# Primitives
primitives = { path = "../primitives", features = ["postgres"] }
adapter = { version = "0.1", path = "../adapter" }
chrono = { version = "0.4", features = ["serde"] }
hex = "0.3.2"
# CLI
clap = "2.33.0"
# Server
tokio = { version = "0.2.9", features = ["macros", "rt-core"] }
hyper = { version = "0.13", features = ["stream"] }
regex = "1"
# Database
redis = { version = "0.14", features = ["tokio-rt-core"] }
bb8 = { git = "https://github.com/khuey/bb8" }
bb8-postgres = { git = "https://github.com/khuey/bb8", features = ["with-chrono-0_4", "with-serde_json-1"] }

# Migrations
migrant_lib = { version = "0.27", features = ["d-postgres"] }
# Logger
slog = { version = "^2.2.3", features = ["max_level_trace"] }
# Serde
serde = { version = "^1.0", features = ['derive'] }
serde_json = "^1.0"
serde_urlencoded = "0.6.1"
# Other
lazy_static = "1.4.0"