# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 512
wait_time = 40000

aggr_throttle = 40000
events_find_limit = 100
msgs_find_limit = 10

heartbeat_time = 60000
health_threshold_promilles = 970
health_unsignable_promilles = 770
propagation_timeout = 3000

fetch_timeout = 10000
validator_tick_timeout = 10000

ip_rate_limit = { type = 'ip', timeframe = 1200000 }
sid_rate_limit = { type = 'sid', timeframe = 0 }
ethereum_core_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'
ethereum_network = 'http://localhost:8545'
ethereum_adapter_relayer = 'https://relayer.adex.network'

creators_whitelist = []
minimal_deposit = "0"
minimal_fee = "0"
token_address_whitelist = ['0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359', '0x6B175474E89094C44Da98b954EedeAC495271d0F']
validators_whitelist = []
