[package]
name = "adapter"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>, Omidiora Samuel <sam@adex.network>"]
edition = "2018"

[dependencies]
primitives = { path = "../primitives" }
# Time handling
chrono = "0.4"
# To/From Hex
hex = "0.4"
serde = { version = "^1.0", features = ['derive'] }
serde_json = "1.0"
serde-hex = "0.1.0"
# Ethereum
web3 = { git = "https://github.com/elpiel/rust-web3" }
eth_checksum = "0.1.1"
tiny-keccak = "1.5"
ethstore = { git = "https://github.com/elpiel/openethereum", branch = "remove-dir-depenedency-for-ethstore" }
# API client
reqwest = { version = "0.10", features = ["json"] }

sha2 = "0.8.0"
base64 = "0.10.1"
lazy_static = "1.4.0"
# Futures
futures = { version = "0.3.1", features = ["compat"] }
async-trait = "0.1.40"

[dev-dependencies]
byteorder = "1.3"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
wiremock = "0.3"
