[package]
name = "validator_worker"
version = "0.1.0"
authors = ["Lachezar Lechev <lachezar@adex.network>", "Samparsky <sam@adex.network>"]
edition = "2018"

[lib]
name = "validator_worker"
path = "src/lib.rs"

[dependencies]
# Primitve
primitives = { path = "../primitives" }
adapter = { version = "0.1", path = "../adapter" }
chrono = { version = "0.4", features = ["serde"] }
num = "0.3"
num-traits = "0.2"
# To/From Hex
hex = "0.4"
byteorder = "1.3"
# Logging
slog = { version = "^2.5.2" , features = ["max_level_trace"] }
# Futures
futures = "0.3"
# Concurrency
tokio = { version = "0.2", features = ["time"] }
# API client
reqwest = { version = "0.10", features = ["json"] }
# Configuration
lazy_static = "1.3"
# (De)Serialization
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
# CLI
clap = "2.33.0"
